//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouletteApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RouletteApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The apiKey is not valid.
        /// </summary>
        public static string Status0 {
            get {
                return ResourceManager.GetString("Status0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Roulette is activate.
        /// </summary>
        public static string Status1 {
            get {
                return ResourceManager.GetString("Status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is not valid.
        /// </summary>
        public static string Status2 {
            get {
                return ResourceManager.GetString("Status2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value bet is not valid.
        /// </summary>
        public static string Status3 {
            get {
                return ResourceManager.GetString("Status3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color is not valid.
        /// </summary>
        public static string Status4 {
            get {
                return ResourceManager.GetString("Status4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Roulette is not activate.
        /// </summary>
        public static string Status5 {
            get {
                return ResourceManager.GetString("Status5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RouletteId is not valid.
        /// </summary>
        public static string Status97 {
            get {
                return ResourceManager.GetString("Status97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The apiKey is required.
        /// </summary>
        public static string Status98 {
            get {
                return ResourceManager.GetString("Status98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to execute query on DataBase.
        /// </summary>
        public static string Status99 {
            get {
                return ResourceManager.GetString("Status99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Roulette was created successfully.
        /// </summary>
        public static string StatusSuccess1 {
            get {
                return ResourceManager.GetString("StatusSuccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Roulette was activated successfully.
        /// </summary>
        public static string StatusSuccess2 {
            get {
                return ResourceManager.GetString("StatusSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bet was created successfully.
        /// </summary>
        public static string StatusSuccess3 {
            get {
                return ResourceManager.GetString("StatusSuccess3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Roulette was closed successfully.
        /// </summary>
        public static string StatusSuccess4 {
            get {
                return ResourceManager.GetString("StatusSuccess4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bet list return successfully.
        /// </summary>
        public static string StatusSuccess5 {
            get {
                return ResourceManager.GetString("StatusSuccess5", resourceCulture);
            }
        }
    }
}
